### ISSUE TITLE
check-mdadm plugin doesnt switch to warning or critical if an raid is degraded

### ISSUE THREAD

**Issue by n1ete** [bloonix/bloonix-plugins-linux#10]
i think the syntax is wrong to show us an degraded and active raid as critical or as an warning in bloonix, as long as the raid is also active. 
a raid is normaly still active after its degraded from a faulty drive. so what do we have to change that as soon as a raid is degraded but still active, it showed us as critical or at least as a warning in bloonix?!
thanks for any help

**Comment by j-schulz** [comment]
Thank you for the report. Fixed in bloonix-plugins-linux-0.68.
