### ISSUE TITLE
check-updates: Why 'dnf clean metadata'?

### ISSUE THREAD

**Issue by LicoMonch** [bloonix/bloonix-plugins-linux#5]
Hi,

in check-linux-updates - if dnf is available - it is used this way:
1. dnf clean metadata
2. dnf updateinfo
3. parse and check output of (2.)

Is there any reason to clear the metadata on every run?
dnf then has to rebuild all the metadata at step (2.).
To entirely rebuild the metadata-set for each repository is a huge task and can take a lot of resources - time, bandwidth, memory and CPU .. dnf and the expiration setting of repositories was made especially to avoid such 'bad' tasks everytime a dnf-command is called .. so you somehow revert some of the improvements of dnf.

Imho: The better way would be to do a 'dnf --refresh check-update' in step (1.).
The metadata gets flaged es expired and dnf will check  for changes in the configured repositories and update its metadata if needed, so that 'updateinfo' gets fresh data.

Greetings,
Lico

**Comment by LicoMonch** [comment]
Just reread some docs.
If you use 'dnf --refresh'. You could skip step (1.) entirely and just do:

1. dnf --refresh udpateinfo
2. parse and check output of (1.)

Lico

**Comment by j-schulz** [comment]
The target is that if check-linux-updates is running that it does not check cached data.

If the script is running then it should check if now(!) are updates available and not if some metadata expires from the cache.

I'm not sure how it works correctly but it seems to me that dnf --refresh does some spooky things:

https://lists.fedoraproject.org/pipermail/users/2015-August/464209.html

**Comment by j-schulz** [comment]
Ok, I could skipt 1. but it would be still the same, because --refresh marks the metadata as expired and forces dnf to download the latest metadata. Right?

**Comment by LicoMonch** [comment]
closed with https://forum.bloonix.org/index.php/Thread/166-check-linux-updates-dnf/?postID=1236#post1236
