### ISSUE TITLE
check_ifstat doesn't parse interfaces with hyphen

### ISSUE THREAD

**Issue by sventhomsen** [bloonix/bloonix-plugins-linux#9]
check_ifstat uses a regex to pass /proc/net/dev:

see: 

> next unless $line =~ /^\s*(\w+):\s*(.*)/;

\w matches any single character classified as a “word” character (alphanumeric or “_”) but not "-".

"internal-net", "dmz-1",... are valid interface names, bloonix right now can't monitor these.

**Comment by j-schulz** [comment]
Hey ho, I think I never expected that someone would use "-" within interface names :-)

Gimme some seconds ....

**Comment by j-schulz** [comment]
Fixed. bloonix-plugins-linux-0.65 is ready for installation.
